#disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are turned off by default, so you need to opt-in
    - empty_count # Find all the available rules by running: `swiftlint rules`

included:
    - iOS-skeleton-Matea
excluded:
    - Pods

identifier_name:
 max_length:
  warning: 45
  error: 60
 min_length:
  warning: 1

line_length:
    warning: 120
    error: 200
    ignores_function_declarations: true

weak_delegate: error
large_tuple:
  warning: 4
  error: 6
function_parameter_count:
  warning: 6
  error: 8

excluded:
- Pods

