using_bundler = defined? Bundler
unless using_bundler
  puts "\nPlease re-run using:".red
  puts "  bundle exec pod install\n\n"
  exit(1)
end

platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

workspace 'iOS-skeleton-Matea'

#install! 'cocoapods',
#:generate_multiple_pod_projects => true,
#:incremental_installation => true

def pod_communication
  pod 'RxCocoa', '~> 5.0'
  pod 'RxSwift', '~> 5.0'
end

def pod_networking
  pod 'RestBird'
  pod 'ReachabilitySwift', '~> 5.0'
end

target 'iOS-skeleton-Matea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-skeleton-Matea

	pod 'SwiftGen'
  	pod 'SwiftLint'	
  
	# RxSwift
  	
	pod_communication

	target 'Core' do
		inherit! :search_paths
    		
		pod_networking	
	end

  # Use this for client-demo presentation
  # It shows touch feedback while presenting
  # pod 'ShowTime', :configurations => ['Debug']
end